apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: www
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: nginx
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  namespace: www
spec:
  selector:
    app: myapp
  ports:
    - port: 80
  type: LoadBalancer
